version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - PROJECT_WORKING_DIR=${PROJECT_WORKING_DIR}
    volumes:
      - ./src:/src
    env_file:
      # - ./src/.env
      - ./.env